stages:
  - build
  - test
  - deploy

build-windows:
  stage: build
  script:
    - cmake -B build -S . #-DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp "stata/edm_Windows_x64.plugin" "C:\Users\EDM\Dropbox\ci-builds"
  artifacts:
    paths:
    - stata/edm_Windows_x64.plugin
    # - stata/gbench.exe
    # - build/Release/*.dll
  tags:
    - windows-runner

test-windows:
  stage: test
  dependencies:
    - build-windows
  before_script:
    - cd stata
    - move-item -force cut-down-test.log reference.log
  script:
    - cmd.exe /c "C:\Program Files\Stata16\StataMP-64.exe" -e -q cut-down-test.do
    - cmd.exe /c "fc /W reference.log cut-down-test.log"
  tags:
    - windows-runner

dropbox-deploy-windows:
  variables:
    PLUGIN_FILE: "edm_Windows_x64.plugin"
  stage: deploy
  dependencies:
    - build-windows
  only:
    - master
  before_script:
    - cd stata
  script:
    - cp "${PLUGIN_FILE}" "C:\Users\EDM\Dropbox\ci-builds-master"
  tags:
    - windows-runner

perf-windows:
  stage: deploy
  dependencies:
    - build-windows
  before_script:
    # - cp build/Release/*.dll stata
    - cd stata
  script:
    - echo "Need to fix benchmarking"
    # - ./gbench.exe
  tags:
    - windows-runner

build-mac:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
    - export VCPKG_TARGET_TRIPLET=arm64-osx
    - export VCPKG_DEFAULT_TRIPLET=arm64-osx
  script:
    - cmake -B build -S . # -DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp stata/edm_MacOSX_x64.plugin ~/Dropbox/EDM/ci-builds
  artifacts:
    paths:
      - stata/edm_MacOSX_x64.plugin
      # - stata/gbench
  tags:
    - mac-arm64

test-mac:
  stage: test
  dependencies:
    - build-mac
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - /Applications/Stata/StataMP.app/Contents/MacOS/StataMP -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - mac-arm64

dropbox-deploy-mac:
  variables:
    PLUGIN_FILE: "edm_MacOSX_x64.plugin"
  stage: deploy
  dependencies:
    - build-mac
  only:
    - master
  before_script:
    - cd stata
  script:
    - cp "${PLUGIN_FILE}" ~/Dropbox/EDM/ci-builds-master/
  tags:
    - mac-arm64

perf-mac:
  stage: deploy
  dependencies:
    - build-mac
  before_script:
    - cd stata
  script:
    - echo "Need to fix benchmarking"
    # - ./gbench
  tags:
    - mac-arm64

build-ubuntu:
  stage: build
  before_script:
    - export VCPKG_ROOT=/usr/local/vcpkg/
    - export CMAKE_PREFIX_PATH=/usr/local/vcpkg/installed/
  script:
    - mkdir build
    - cd build
    - cmake .. #-DBUILD_GBENCH=TRUE
    - cd ..
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp stata/edm_Unix_x64.plugin ~/Dropbox/ci-builds
    - cp stata/edm.ado ~/Dropbox/ci-builds
  artifacts:
    paths:
      - stata/edm_Unix_x64.plugin
      # - stata/gbench
  tags:
    - ubuntu-runner

test-ubuntu:
  stage: test
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - stata -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - ubuntu-runner

dropbox-deploy-ubuntu:
  variables:
    PLUGIN_FILE: "edm_Unix_x64.plugin"
  stage: deploy
  dependencies:
    - build-ubuntu
  only:
    - master
  before_script:
    - cd stata
  script:
    - cp "${PLUGIN_FILE}" ~/Dropbox/ci-builds-master/
    - cp edm.ado ~/Dropbox/ci-builds-master/
  tags:
    - ubuntu-runner

perf-ubuntu:
  stage: deploy
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
  script:
    - echo "Need to fix benchmarking"
    # - ./gbench
  tags:
    - ubuntu-runner
