variables:
  TARGET_FOLDER: "/Apps/edm-master-ci"
  UPLOADER_FETCH_URL: "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  UPLOADER: "dropbox_uploader.sh"
  UPLOADER_CONFIG: "~/.dropbox_uploader"

stages:
  - build
  - test
  - deploy

build-windows:
  stage: build
  script:
    - cmake -B build -S .
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
    - stata/edm_Windows_x64.plugin
  tags:
    - windows-runner

test-windows:
  stage: test
  dependencies:
    - build-windows
  before_script:
    - cd stata
    - move-item -force cut-down-test.log reference.log
  script:
    - cmd.exe /c "C:\Program Files\Stata16\StataMP-64.exe" -e -q cut-down-test.do
    - cmd.exe /c "fc /W reference.log cut-down-test.log"
  tags:
    - windows-runner

build-mac:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
    - export PATH="/Users/user175910/bin:$PATH"
  script:
    - cmake -B build -S .
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/edm_MacOSX_x64.plugin
  tags:
    - mac-runner

test-mac:
  stage: test
  dependencies:
    - build-mac
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - ~/Stata/StataMP.app/Contents/MacOS/StataMP -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - mac-runner

build-ubuntu:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/edm_Unix_x64.plugin
  tags:
    - ubuntu-stata-runner

test-ubuntu:
  stage: test
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - stata -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - ubuntu-stata-runner

dropbox-deploy:
  variables:
    PLUGIN_FILE: "edm_Unix_x64.plugin"
  stage: deploy
  dependencies:
    - build-ubuntu
  only:
    - master
  before_script:
    - cd stata
    - curl "${UPLOADER_FETCH_URL}" -o "${UPLOADER}"
    - echo "OAUTH_ACCESS_TOKEN=${DROPBOX_DEPLOY_TOKEN}" > "${UPLOADER_CONFIG}"
  script:
    - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" mkdir "${TARGET_FOLDER}" &>/dev/null || echo "Target folder exists"
    - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" upload "${PLUGIN_FILE}" "${TARGET_FOLDER}"
  after_script:
    - rm -f "${UPLOADER}"
    - rm -f "${UPLOADER_CONFIG}"
  tags:
    - ubuntu-stata-runner
  
