stages:
  - build
  - test
  - deploy

build-windows:
  stage: build
  script:
    - cmake -B build -S . -DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp "bin/edm_Windows_x64.plugin" "C:\Users\EDM\Dropbox\ci-builds"
  artifacts:
    paths:
    - bin/edm_Windows_x64.plugin
    - test/gbench.exe
  tags:
    - windows-runner

test-windows:
  stage: test
  dependencies:
    - build-windows
  before_script:
    - cd test
    - cp edm_Windows_x64.plugin edm.plugin
    - move-item -force cut-down-test.log reference.log
  script:
    - cmd.exe /c "C:\Program Files\Stata17\StataMP-64.exe" -e -q cut-down-test.do
    - cmd.exe /c "fc /W reference.log cut-down-test.log"
  tags:
    - windows-runner

dropbox-deploy-windows:
  variables:
    PLUGIN_FILE: "edm_Windows_x64.plugin"
  stage: deploy
  dependencies:
    - build-windows
  only:
    - master
  before_script:
    - cd test
  script:
    - cp "${PLUGIN_FILE}" "C:\Users\EDM\Dropbox\ci-builds-master"
  tags:
    - windows-runner

perf-windows:
  stage: deploy
  dependencies:
    - build-windows
  before_script:
    - cd test
  script:
    - ./gbench.exe
  tags:
    - windows-runner

build-mac-arm:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
    - export VCPKG_TARGET_TRIPLET=arm64-osx
    - export VCPKG_DEFAULT_TRIPLET=arm64-osx
    - export ARMMODE
  script:
    - cmake -B build -S . -DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp bin/edm_MacOSX_arm.plugin ~/Dropbox/EDM/ci-builds
  artifacts:
    paths:
      - bin/edm_MacOSX_arm.plugin
      - test/gbench
  tags:
    - mac-arm64

build-mac-x64:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
    - export VCPKG_TARGET_TRIPLET=x64-osx
    - export VCPKG_DEFAULT_TRIPLET=x64-osx
    - unset ARMMODE
  script:
    - env /usr/bin/arch -x86_64 cmake -B build -S . -DBUILD_GBENCH=TRUE
    - env /usr/bin/arch -x86_64 cmake --build build --config release
    - env /usr/bin/arch -x86_64 cmake --build build --config release --target install
  after_script:
    - cp bin/edm_MacOSX_x64.plugin ~/Dropbox/EDM/ci-builds
  artifacts:
    paths:
      - bin/edm_MacOSX_x64.plugin
      - test/gbench
  tags:
    - mac-arm64


test-mac-arm:
  stage: test
  dependencies:
    - build-mac-arm
  before_script:
    - cd test
    - cp edm_MacOSX_arm.plugin edm.plugin
    - mv cut-down-test.log reference.log
  script:
    - /Applications/Stata/StataMP.app/Contents/MacOS/StataMP -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - mac-arm64

dropbox-deploy-mac-arm:
  stage: deploy
  dependencies:
    - build-mac-arm
  only:
    - master
  before_script:
    - cd test
  script:
    - cp "edm_MacOSX_arm.plugin" ~/Dropbox/EDM/ci-builds-master/
  tags:
    - mac-arm64

dropbox-deploy-mac-x64:
  stage: deploy
  dependencies:
    - build-mac-x64
  only:
    - master
  before_script:
    - cd test
  script:
    - cp "edm_MacOSX_x64.plugin" ~/Dropbox/EDM/ci-builds-master/
  tags:
    - mac-arm64


perf-mac:
  stage: deploy
  dependencies:
    - build-mac
  before_script:
    - cd test
  script:
    - ./gbench
  tags:
    - mac-arm64

build-ubuntu:
  stage: build
  before_script:
    - export VCPKG_ROOT=/usr/local/vcpkg/
    - export CMAKE_PREFIX_PATH=/usr/local/vcpkg/installed/
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_GBENCH=TRUE
    - cd ..
    - cmake --build build --config release
    - cmake --build build --config release --target install
  after_script:
    - cp bin/edm_Unix_x64.plugin ~/Dropbox/ci-builds
    - cp stata/edm.ado ~/Dropbox/ci-builds
  artifacts:
    paths:
      - bin/edm_Unix_x64.plugin
      - test/gbench
  tags:
    - ubuntu-runner

test-ubuntu:
  stage: test
  dependencies:
    - build-ubuntu
  before_script:
    - cd test
    - cp edm_Unix_x64.plugin edm.plugin
    - mv cut-down-test.log reference.log
  script:
    - stata -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - ubuntu-runner

dropbox-deploy-ubuntu:
  variables:
    PLUGIN_FILE: "edm_Unix_x64.plugin"
  stage: deploy
  dependencies:
    - build-ubuntu
  only:
    - master
  before_script:
    - cd test
  script:
    - cp "${PLUGIN_FILE}" ~/Dropbox/ci-builds-master/
    - cp edm.ado ~/Dropbox/ci-builds-master/
  tags:
    - ubuntu-runner

perf-ubuntu:
  stage: deploy
  dependencies:
    - build-ubuntu
  before_script:
    - cd test
  script:
    - ./gbench
  tags:
    - ubuntu-runner
