image: curoky/vcpkg:debian10

build:
  stage: build
  before_script:
    - apt update && apt -y install make cmake g++-9
    - export VCPKG_ROOT=/opt/vcpkg/
    - export CXX=g++-9
  script:
    - cmake -B build -S .
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/smap_driver
      - stata/edm_Unix_x64.plugin
      - stata/test1.h5
  tags:
    - ubuntu-docker

# run tests using the binary built before
test:
  stage: test
  dependencies:
    - build
  before_script:
    - cd stata
    - ldd edm_Unix_x64.plugin
    - ldd -v edm_Unix_x64.plugin
    - ldd -u edm_Unix_x64.plugin
    - export LD_LIBRARY_PATH=`pwd`
  script:
    - ./smap_driver test1.h5
    - echo $?
  tags:
    - ubuntu-docker
