build-windows:
  stage: build
  script:
    - cmake -B build -S . -DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
    - stata/edm_Windows_x64.plugin
    - stata/gbench.exe
    - build/Release/*.dll
  tags:
    - windows-runner

test-windows:
  stage: test
  dependencies:
    - build-windows
  before_script:
    - cd stata
    - move-item -force cut-down-test.log reference.log
  script:
    - cmd.exe /c "C:\Program Files\Stata16\StataMP-64.exe" -e -q cut-down-test.do
    - cmd.exe /c "fc /W reference.log cut-down-test.log"
  tags:
    - windows-runner

perf-windows:
  stage: deploy
  dependencies:
    - build-windows
  before_script:
    - cp build/Release/*.dll stata
    - cd stata
  script:
    - ./gbench.exe
  tags:
    - windows-runner

build-mac:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
    - export PATH="/Users/user175910/bin:$PATH"
  script:
    - cmake -B build -S . -DBUILD_GBENCH=TRUE
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/edm_MacOSX_x64.plugin
      - stata/gbench
  tags:
    - mac-runner

test-mac:
  stage: test
  dependencies:
    - build-mac
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - ~/Stata/StataMP.app/Contents/MacOS/StataMP -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - mac-runner

perf-mac:
  stage: deploy
  dependencies:
    - build-mac
  before_script:
    - cd stata
  script:
    - ./gbench
  tags:
    - mac-runner

build-ubuntu:
  stage: build
  before_script:
    - export VCPKG_ROOT=~/vcpkg/
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_GBENCH=TRUE
    - cd ..
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/edm_Unix_x64.plugin
      - stata/gbench
  tags:
    - ubuntu-stata-runner

test-ubuntu:
  stage: test
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
    - mv cut-down-test.log reference.log
  script:
    - stata -e -q cut-down-test.do
    - diff -B reference.log cut-down-test.log
  tags:
    - ubuntu-stata-runner

perf-ubuntu:
  stage: deploy
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
  script:
    - ./gbench
  tags:
    - ubuntu-stata-runner
