build-ubuntu:
  stage: build
  script:
    - cmake -B build -S .
    - cmake --build build --config release
    - cmake --build build --config release --target install
  artifacts:
    paths:
      - stata/edm_Unix_x64.plugin
  tags:
    - ubuntu-stata-runner

test-ubuntu:
  stage: test
  dependencies:
    - build-ubuntu
  before_script:
    - cd stata
    - mv cut-down-test-output.log reference.log
  script:
    - stata -b cut-down-test.do
    - cmp -s reference.log cut-down-test-output.log
  tags:
    - ubuntu-stata-runner