site_name: EDM MDAP collaboration

nav:
    - Home: index.md
    - Stata EDM plugin: plugin.md
    - Other EDM implementations: other_edm.md
    - Infrastructure: infrastructure.md

theme:
  name: readthedocs
  hljs_languages:
        - stata

